name: thai_tech_event_calendar
description: Thai Tech Event Calendar App

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  font_awesome_flutter: 6.0.0
  flutter_markdown: "^0.1.3"
  path_provider: "^0.4.0"
  url_launcher: "^3.0.0"
  sqflite: any
  fluro: "^1.2.1"
  intl: "^0.15.2"
 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
